# https://gohugo.io/getting-started/configuration/
# In local "development" builds, baseURL is always switched to localhost
# For "production" of the site, AWS Amplify deploys with "environment" - see the production/config.toml for overrides
baseURL = "http://developer.rhino3d.com" #TODO: We mnight need to switch this...
#baseURL = "https://source.rhino3d.com"
title = "Rhino Developer Docs"
defaultContentLanguage = "en"
assetDir = "static"
defaultContentLanguageInSubdir = "true"
timeout = 60000
theme = "rhino3d.com-theme"
metaDataFormat = "toml"
disable404 = "true" # we custom generate our 404 page based on a template for localization purposes
enableGitInfo = "true"
disableKinds = ["RSS"]

[security.funcs]
    getenv = ['^HUGO_', 'MCNEEL_REGION']

[params]
  nwo = "mcneel/developer.rhino3d.com" # github repository (name with owner)
  latestRhinoVersion = 7
  supportedPlatforms = "Windows and macOS"
  siteRootURL = "/" # used in navigation banner
  rhinoURL = "https://www.rhino3d.com"
  rhinoURLNewSource = "https://www.rhino3d.com/new-source"
  navBarShouldResize = false
  supportsChat = false
  siteNavLogo = "/images/rhinodevlogo.png"
  logoTitleTextPrimary = "Rhino"
  logoTitleTextSecondary = "Developer"
  protectedMark = ""
  discourseURL = "https://discourse.mcneel.com"
  forestryBaseURL = "https://app.forestry.io/sites/9bs6ghwu05ji2w/#/pages/content"
  facebookURL = "https://www.facebook.com/McNeelRhinoceros/"
  twitterURL = "https://twitter.com/bobmcneel"
  linkedinURL = "https://www.linkedin.com/groups/75313/"
  youtubeURL = "https://www.youtube.com/user/RhinoGuide/videos"
  vimeoURL = "https://vimeo.com/rhino"
  bloggerURL = "http://blog.rhino3d.com/"
  food4rhinoURL = "https://www.food4rhino.com"
[params.tableOfContents]
    endLevel = 3
    startLevel = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true    
    noClasses = true
    style = "vs"
    tabWidth = 4

# 2020-03-19, Scott Davidson. Loads the Google fonts in the Head.html
googlefonts = [
    "Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic",
    "Roboto+Mono:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic"
]

# https://gohugo.io/templates/sitemap-template/
[sitemap]
  changefreq = "daily"

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[languages]
  [languages.en]
    title = "Rhino Developer Docs"
    description = "Rhino is a 3D modeler used to create, edit, analyze, document, render, animate, and translate NURBS* curves, surfaces, and solids, point clouds, SubD surfaces, and polygon meshes. There are no limits on complexity, degree, or size beyond those of your hardware."
    author = "Robert McNeel & Associates"
    weight = 1
    languageName = "English"
    contentDir = "content/en"
    [languages.en.params]
      copyright = "Copyright © 1993-{year} Robert McNeel & Associates. All Rights Reserved."
      siteNav = "original-site-navigation"
      imagesDir = "images"
      docLang = "en-us" # the language code used on docs.mcneel.com
    [languages.en.taxonomies]
      "tag" = "tags"
      "category" = "categories"
      "platform" = "platforms"
      "task" = "tasks"
      "level" = "levels"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "guides"
        pre = ""
        post = ""
        name = "Guides"
        url = "/guides"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "samples"
        pre = ""
        post = ""
        name = "Samples"
        url = "/samples"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "api"
        pre = ""
        post = ""
        name = "API"
        url = "/api"
        title = ""
        weight = 4
      [[languages.en.menu.main]]
        identifier = "videos"
        pre = ""
        post = ""
        name = "Videos"
        url = "/videos"
        title = ""
        weight = 5
      [[languages.en.menu.main]]
        identifier = "community"
        pre = ""
        post = ""
        name = "Community"
        url = "https://discourse.mcneel.com/c/rhino-developer"
        title = ""
        weight = 6
